image:
  distribution: debian
  release: buster
  description: |-
    Debian {{ image.release }}
  architecture: x86_64

source:
  downloader: debootstrap
  url: http://deb.debian.org/debian
  keyserver: hkp://keyserver.ubuntu.com:80
  keys:
    - 0x126C0D24BD8A2942CC7DF8AC7638D0442B90D010
    - 0xA1BD8E9D78F7FE5C3E65D8AF8B48AD6246925553
    - 0x6D33866EDD8FFA41C0143AEDDCC9EFBF77E11517
    - 0x80D15823B7FD1561F9F7BCDDDC30D7C23CBBABEE
targets:
  lxc:
    create-message: |-
      You just created an {{ image.description }} container.

      To enable SSH, run: apt install openssh-server
      No default root or user password are set by LXC.

    config:
      - type: all
        before: 5
        content: |-
          lxc.include = LXC_TEMPLATE_CONFIG/ubuntu.common.conf

      - type: user
        before: 5
        content: |-
          lxc.include = LXC_TEMPLATE_CONFIG/ubuntu.userns.conf

      - type: all
        after: 4
        content: |-
          lxc.include = LXC_TEMPLATE_CONFIG/common.conf

      - type: user
        after: 4
        content: |-
          lxc.include = LXC_TEMPLATE_CONFIG/userns.conf

          lxc.arch = {{ image.architecture_personality }}

files:
 - path: /etc/hostname
   generator: hostname

 - path: /etc/hosts
   generator: hosts

 - path: /etc/resolvconf/resolv.conf.d/original
   generator: remove

 - path: /etc/resolvconf/resolv.conf.d/tail
   generator: remove

 - path: /etc/machine-id
   generator: remove

 - path: /etc/network/interfaces
   generator: dump
   content: |-
     # This file describes the network interfaces available on your system
     # and how to activate them. For more information, see interfaces(5).

     # The loopback network interface
     auto lo
     iface lo inet loopback

     auto eth0
     iface eth0 inet dhcp

 - path: /etc/init/lxc-tty.conf
   generator: upstart-tty
   releases:
    - trusty

 - name: meta-data
   generator: cloud-init
   variants:
    - cloud

 - name: network-config
   generator: cloud-init
   variants:
    - cloud

 - name: user-data
   generator: cloud-init
   variants:
    - cloud

 - name: vendor-data
   generator: cloud-init
   variants:
    - cloud

packages:
  manager: apt
  update: true
  cleanup: true

  repositories:
    - name: sources.list
      url: |-
        deb http://deb.debian.org/debian {{ image.release }} main
        deb http://security.debian.org/debian-security {{ image.release }}/updates main

  sets:
    - packages:
      - dialog
      - ifupdown
      - init
      - iproute2
      - isc-dhcp-client
      - locales
      - netbase
      - net-tools
      - openssh-client
      - vim
      action: install

    - packages:
      - cloud-init
      action: install
      variants:
       - cloud

actions:
  - trigger: post-packages
    action: |-
      #!/bin/sh
      set -eux

      # Cleanup underlying /run
      mount -o bind / /mnt
      rm -rf /mnt/run/*
      umount /mnt

      # Cleanup temporary shadow paths
      rm /etc/*-

mappings:
  architecture_map: debian