apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <nom_pv_claim>
  namespace: <namespace>
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: <taille_pv>
  volumeName: <nom_pv>
