apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: <nom du rolebinding>
  namespace: <namespace>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: <namespace>-full-access
subjects:
- kind: ServiceAccount
  name: <nom du service account>